-- Roles y privilegios SQL: BBDD clinica_privada

CREATE ROLE admin WITH LOGIN PASSWORD 'C2GnFn@v9M8.';
CREATE ROLE consultas WITH LOGIN PASSWORD '4WL6kcY9-kjE';
CREATE ROLE replica WITH LOGIN REPLICATION PASSWORD '4WL6kcY9-kjE';

GRANT CONNECT ON DATABASE clinica_privada TO admin, consultas;
GRANT USAGE ON SCHEMA public TO admin, consultas;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO admin;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO consultas;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO consultas;

CREATE ROLE escritura WITH LOGIN PASSWORD '4WL6kcY9-kjE';
GRANT CONNECT ON DATABASE clinica_privada TO escritura;
GRANT USAGE ON SCHEMA public TO escritura;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO escritura;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO escritura;

